### ISSUE TITLE
Could not find module 'kernel32' error on Xbox One

### ISSUE THREAD

**Issue by cboRD181** [watchedsyncforkodi/service.watchedsync#6]
https://paste.kodi.tv/goboseferu

I tried using the default Kodi skin as per the other [similar issue](https://github.com/watchedsyncforkodi/service.watchedsync/issues/5) but to no avail. 

Running on an Xbox One.  I started the debug with the addon disabled, and attempted to enable it a few minutes after startup so the log would be less cluttered, but the error is the same when the addon is enabled at startup.  I have virtually the same build on MacOS and the addon works as expected.

**Comment by watchedsyncforkodi** [comment]
hmm, looking at stack trace it seems there is a problem when importing one of the external modules. This issue hasn't been reported by other Windows users so wonder if it just affects Xbox One.

Only thing that seemed relevant on searching Google was an issue with Kodi 19.3 on Xbox but that was supposedly fixed in 19.4 and your logs indicate you are running 19.4.

I'll log it with the upstream module

**Comment by cboRD181** [comment]
Yeah Xbox has unfortunately had several problems with python, including on 19.4.  I should have noted earlier I'm running a nightly build that implemented this [PR](https://github.com/xbmc/xbmc/pull/22023), if that's helpful in identifying the cause.

**Comment by luanche** [comment]
Hello, is there any update for this issue. I'm still suffering on this error with Xbox Serise S :(

**Comment by watchedsyncforkodi** [comment]
I believe that code path was disabled months ago so I wouldn't expect this issue to be ongoing. To confirm can you provide a debug log on the Xbox. Follow the instructions found at [Kodi Logfile Uploader Add-on](https://kodi.wiki/view/Log_file/Easy) and add the returned URL to the issue text.

**Comment by luanche** [comment]
> I believe that code path was disabled months ago so I wouldn't expect this issue to be ongoing. To confirm can you provide a debug log on the Xbox. Follow the instructions found at [Kodi Logfile Uploader Add-on](https://kodi.wiki/view/Log_file/Easy) and add the returned URL to the issue text.

Hello, thank you for your reply. There is the [log](https://paste.kodi.tv/omudikikub).
```
2024-04-22 19:35:50.557 T:4860     info <general>: CServiceAddonManager: failed to stop service.watchedsync (may have ended)
2024-04-22 19:35:51.895 T:4312    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'FileNotFoundError'>
                                                   Error Contents: Could not find module 'kernel32' (or one of its dependencies). Try using the full path with constructor syntax.
                                                   Traceback (most recent call last):
                                                     File "Q:\Users\UserMgr11\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\service.watchedsync\service.py", line 21, in <module>
                                                       import fasteners
                                                     File "Q:\Users\UserMgr11\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\service.watchedsync\resources\lib\fasteners\__init__.py", line 28, in <module>
                                                       from fasteners.process_lock import interprocess_locked
                                                     File "Q:\Users\UserMgr11\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\service.watchedsync\resources\lib\fasteners\process_lock.py", line 513, in <module>
                                                       import fasteners.pywin32.pywintypes as pywintypes
                                                     File "Q:\Users\UserMgr11\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\service.watchedsync\resources\lib\fasteners\pywin32\pywintypes.py", line 1, in <module>
                                                       from ctypes import c_void_p
                                                     File "S:\Program Files\WindowsApps\XBMCFoundation.Kodi_21.0.0.70_x64__4n2hpmxwrvr6p\system\python\Lib\ctypes\__init__.py", line 468, in <module>
                                                       GetLastError = windll.kernel32.GetLastError
                                                     File "S:\Program Files\WindowsApps\XBMCFoundation.Kodi_21.0.0.70_x64__4n2hpmxwrvr6p\system\python\Lib\ctypes\__init__.py", line 443, in __getattr__
                                                       dll = self._dlltype(name)
                                                     File "S:\Program Files\WindowsApps\XBMCFoundation.Kodi_21.0.0.70_x64__4n2hpmxwrvr6p\system\python\Lib\ctypes\__init__.py", line 373, in __init__
                                                       self._handle = _dlopen(self._name, mode)
                                                   FileNotFoundError: Could not find module 'kernel32' (or one of its dependencies). Try using the full path with constructor syntax.
                                                   -->End of Python script error report<--
```
Feel free to let me know if you need more information.

**Comment by watchedsyncforkodi** [comment]
Thanks for the log. Will take a look and see if we can fix.

**Comment by watchedsyncforkodi** [comment]
Calling @luanche and other Xbox users, I pushed a new release v0.3.16 a few mins ago that hopefully has correct fix.

Please try again on Xbox devices. Would like to hear if it now works.
